from sqlalchemy import Column, Integer, String, Text, Float, Boolean, ForeignKey, DateTime, JSON, LargeBinary
from sqlalchemy.sql import func
from app.db.database import Base


class SessionSummary(Base):
    """
    Post-session structured summary generated by Claude.
    One per session. DM reviews/approves before it is committed to long-term memory.
    """
    __tablename__ = "session_summaries"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    session_id = Column(Integer, ForeignKey("sessions.id"), nullable=False, unique=True, index=True)

    # Structured summary (JSON with keys: events, npcs, items, relationships, avatar_updates)
    summary_json = Column(JSON, nullable=True)

    # Plain prose summary (for display)
    summary_text = Column(Text, nullable=True)

    # DM review state
    is_approved = Column(Boolean, nullable=False, default=False)
    reviewed_at = Column(DateTime(timezone=True), nullable=True)

    # Mid-session rolling summaries (JSON list of {"timestamp": ..., "text": ...})
    rolling_summaries = Column(JSON, nullable=True, default=list)


class MemoryChunk(Base):
    """
    A single retrievable memory unit for an avatar.
    Stores text + embedding vector (as bytes) for similarity search.
    """
    __tablename__ = "memory_chunks"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    avatar_id = Column(Integer, ForeignKey("avatars.id"), nullable=False, index=True)
    session_id = Column(Integer, ForeignKey("sessions.id"), nullable=True, index=True)

    # The text of this memory chunk
    text = Column(Text, nullable=False)

    # Embedding vector stored as raw bytes (float32 array)
    embedding = Column(LargeBinary, nullable=True)

    # Metadata
    chunk_type = Column(String(30), nullable=False, default="event")
    # event | npc | item | relationship | backstory | session_summary

    # Source reference
    source_session_id = Column(Integer, ForeignKey("sessions.id"), nullable=True)

    # Importance score (0.0–1.0), used to weight retrieval
    importance = Column(Float, nullable=False, default=0.5)

    # Whether this chunk is active (DM can soft-delete)
    is_active = Column(Boolean, nullable=False, default=True)
