from sqlalchemy import Column, Integer, String, Text, Boolean, DateTime, JSON
from sqlalchemy.sql import func
from app.db.database import Base


class Session(Base):
    __tablename__ = "sessions"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    ended_at = Column(DateTime(timezone=True), nullable=True)

    name = Column(String(200), nullable=False, default="Unnamed Session")
    campaign_name = Column(String(200), nullable=True)

    # Which avatars are participating (JSON list of avatar IDs)
    avatar_ids = Column(JSON, nullable=False, default=list)

    # Avatar modes for this session (JSON dict: avatar_id -> mode)
    avatar_modes = Column(JSON, nullable=False, default=dict)

    # Post-session summary (generated by Claude, DM-reviewed)
    summary = Column(Text, nullable=True)
    summary_approved = Column(Boolean, nullable=False, default=False)

    # Session state
    is_active = Column(Boolean, nullable=False, default=True)
