"""
Coqui XTTS-v2 TTS wrapper.

Loads XTTS-v2 once on startup and exposes:
  - synthesize(): generate audio bytes for a text+emotion combo
  - load_speaker_embedding(): load a cloned voice profile from disk
  - list_speakers(): return built-in speaker names (fallback when no embedding)

Falls back gracefully if TTS library is not installed:
  returns a short silent WAV so the pipeline still functions.
"""

from __future__ import annotations

import io
import wave
import struct
import numpy as np
import structlog
from dataclasses import dataclass, field
from pathlib import Path

log = structlog.get_logger()

# Emotion tag → speaking-rate and energy hints for XTTS conditioning
EMOTION_SPEEDS: dict[str, float] = {
    "quietly":    0.85,
    "whispering": 0.80,
    "urgently":   1.15,
    "tense":      1.05,
    "laughing":   1.10,
    "default":    1.00,
}

# Silence WAV (0.5s, 16kHz mono int16) used as stub when XTTS unavailable
def _silent_wav(duration_s: float = 0.5, sample_rate: int = 24000) -> bytes:
    n = int(sample_rate * duration_s)
    samples = struct.pack(f"<{n}h", *([0] * n))
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(sample_rate)
        wf.writeframes(samples)
    return buf.getvalue()


@dataclass
class SynthesisResult:
    audio_bytes: bytes       # raw WAV bytes
    sample_rate: int = 24000
    duration_s: float = 0.0
    emotion: str = "default"
    text: str = ""


class TTSEngine:
    """
    Singleton XTTS-v2 engine.

    Thread-safe for concurrent synthesis calls from asyncio thread pool.
    Speaker embeddings (gpt_cond_latent + speaker_embedding) are loaded
    per-avatar from .npz files generated by scripts/clone_voice.py.
    """

    SAMPLE_RATE = 24000  # XTTS-v2 native output rate

    def __init__(self, device: str = "cuda"):
        self.device = device
        self._model = None
        self._speakers: dict[int, dict] = {}  # avatar_id → {gpt_cond_latent, speaker_embedding}
        self._load()

    def _load(self) -> None:
        try:
            from TTS.api import TTS
            log.info("tts.loading_xtts2", device=self.device)
            self._model = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(self.device)
            log.info("tts.ready")
        except ImportError:
            log.warning("tts.coqui_not_installed", note="TTS running in silent stub mode")
        except Exception as e:
            log.error("tts.load_failed", error=str(e))

    @property
    def available(self) -> bool:
        return self._model is not None

    # ── Speaker management ────────────────────────────────────────────────

    def load_speaker_embedding(self, avatar_id: int, embedding_path: str) -> bool:
        """
        Load a pre-computed speaker embedding from a .npz file.
        Returns True if successful.
        """
        try:
            data = np.load(embedding_path, allow_pickle=True)
            self._speakers[avatar_id] = {
                "gpt_cond_latent": data["gpt_cond_latent"],
                "speaker_embedding": data["speaker_embedding"],
            }
            log.info("tts.speaker_loaded", avatar_id=avatar_id, path=embedding_path)
            return True
        except Exception as e:
            log.error("tts.speaker_load_failed", avatar_id=avatar_id, error=str(e))
            return False

    def has_speaker(self, avatar_id: int) -> bool:
        return avatar_id in self._speakers

    # ── Synthesis ─────────────────────────────────────────────────────────

    def synthesize(
        self,
        text: str,
        avatar_id: int,
        emotion: str = "default",
        language: str = "en",
        volume: float = 1.0,
    ) -> SynthesisResult:
        """
        Synthesize speech for the given text using the avatar's voice profile.

        Parameters
        ----------
        text      : plain text (emotion tags already stripped by post-processor)
        avatar_id : which avatar's voice embedding to use
        emotion   : drives speaking rate (quietly/urgently/tense/etc.)
        language  : ISO-639-1 language code
        volume    : 0.0–1.0 gain applied to output samples
        """
        if not self.available:
            return SynthesisResult(
                audio_bytes=_silent_wav(0.5),
                sample_rate=self.SAMPLE_RATE,
                duration_s=0.5,
                emotion=emotion,
                text=text,
            )

        speaker = self._speakers.get(avatar_id)

        try:
            import torch
            buf = io.BytesIO()

            if speaker:
                # Cloned voice via speaker conditioning tensors
                import torch
                audio_array = self._model.tts(
                    text=text,
                    language=language,
                    gpt_cond_latent=torch.tensor(speaker["gpt_cond_latent"]),
                    speaker_embedding=torch.tensor(speaker["speaker_embedding"]),
                    speed=EMOTION_SPEEDS.get(emotion, 1.0),
                )
            else:
                # Fallback: use built-in "Claribel Dervla" speaker
                audio_array = self._model.tts(
                    text=text,
                    language=language,
                    speaker="Claribel Dervla",
                    speed=EMOTION_SPEEDS.get(emotion, 1.0),
                )

            # audio_array is a list/ndarray of float32 samples
            samples = np.array(audio_array, dtype=np.float32)

            # Apply volume
            if volume != 1.0:
                samples = samples * volume

            # Clip and convert to int16
            samples_i16 = np.clip(samples * 32767, -32768, 32767).astype(np.int16)
            duration_s = len(samples_i16) / self.SAMPLE_RATE

            with wave.open(buf, "wb") as wf:
                wf.setnchannels(1)
                wf.setsampwidth(2)
                wf.setframerate(self.SAMPLE_RATE)
                wf.writeframes(samples_i16.tobytes())

            return SynthesisResult(
                audio_bytes=buf.getvalue(),
                sample_rate=self.SAMPLE_RATE,
                duration_s=duration_s,
                emotion=emotion,
                text=text,
            )

        except Exception as e:
            log.error("tts.synthesis_failed", error=str(e), text=text[:60])
            return SynthesisResult(
                audio_bytes=_silent_wav(0.5),
                sample_rate=self.SAMPLE_RATE,
                duration_s=0.5,
                emotion=emotion,
                text=text,
            )
