"""
Backchannel Player.

Manages the per-avatar library of pre-generated short audio clips
("mm", "yeah", "right"…) that play during human speech at ~60% volume.

Clips are pre-generated by scripts/generate_backchannels.py and
cached as WAV files in data/backchannels/{avatar_id}/{category}/{text}.wav

Playback is probabilistic:
  - max once per BACKCHANNEL_MIN_GAP seconds of continuous speech
  - 35% chance when eligible
"""

from __future__ import annotations

import random
import time
from pathlib import Path
from dataclasses import dataclass, field

import structlog

from app.config import get_settings

log = structlog.get_logger()
settings = get_settings()

BACKCHANNEL_DIR = Path("data/backchannels")

# Canonical library — used for generation and for selecting what to say
BACKCHANNEL_LIBRARY: dict[str, list[str]] = {
    "neutral":   ["mm", "hmm", "yeah", "right", "uh huh"],
    "surprised": ["oh!", "oh really?", "no way"],
    "agreeing":  ["yeah, exactly", "I think so too", "mm, that's true"],
    "uncertain": ["hmm, maybe...", "I'm not sure", "could be..."],
    "engaged":   ["wait—", "go on", "and then what?"],
}


@dataclass
class BackchannelLibrary:
    """
    Per-avatar pre-generated clip library.

    Clips are keyed by (category, text) → WAV bytes.
    Falls back to None if the WAV file doesn't exist (TTS not yet run).
    """
    avatar_id: int
    clips: dict[tuple[str, str], bytes] = field(default_factory=dict)
    _last_played_at: float = field(default=0.0, init=False)

    def load_from_disk(self) -> int:
        """Load all pre-generated WAV clips for this avatar. Returns count loaded."""
        avatar_dir = BACKCHANNEL_DIR / str(self.avatar_id)
        if not avatar_dir.exists():
            log.debug("backchannel.no_clips_dir", avatar_id=self.avatar_id)
            return 0
        count = 0
        for wav_path in avatar_dir.rglob("*.wav"):
            category = wav_path.parent.name
            text_key = wav_path.stem.replace("_", " ")
            try:
                self.clips[(category, text_key)] = wav_path.read_bytes()
                count += 1
            except IOError as e:
                log.warning("backchannel.load_error", path=str(wav_path), error=str(e))
        log.info("backchannel.loaded", avatar_id=self.avatar_id, count=count)
        return count

    def should_play(self) -> bool:
        """Return True if a backchannel is eligible to play right now."""
        elapsed = time.monotonic() - self._last_played_at
        if elapsed < settings.backchannel_min_gap:
            return False
        return random.random() < settings.backchannel_chance

    def pick(self, category: str = "neutral") -> tuple[str, bytes | None]:
        """
        Pick a random backchannel clip from the given category.

        Returns (text, wav_bytes). wav_bytes is None if no clips loaded.
        """
        options = BACKCHANNEL_LIBRARY.get(category, BACKCHANNEL_LIBRARY["neutral"])
        text = random.choice(options)
        wav = self.clips.get((category, text))

        # Try neighbouring categories if preferred one isn't cached
        if wav is None:
            for cat, texts in BACKCHANNEL_LIBRARY.items():
                for t in texts:
                    w = self.clips.get((cat, t))
                    if w is not None:
                        text, wav = t, w
                        break
                if wav is not None:
                    break

        return text, wav

    def mark_played(self) -> None:
        self._last_played_at = time.monotonic()


class BackchannelManager:
    """
    Manages BackchannelLibrary instances for all active avatars.
    """

    def __init__(self):
        self._libraries: dict[int, BackchannelLibrary] = {}

    def register(self, avatar_id: int) -> None:
        if avatar_id not in self._libraries:
            lib = BackchannelLibrary(avatar_id=avatar_id)
            lib.load_from_disk()
            self._libraries[avatar_id] = lib

    def unregister(self, avatar_id: int) -> None:
        self._libraries.pop(avatar_id, None)

    def get_clip(
        self, avatar_id: int, category: str = "neutral"
    ) -> tuple[str, bytes | None] | None:
        """
        Return (text, wav_bytes) if this avatar is eligible for a backchannel
        right now, or None if not eligible / no clips.
        """
        lib = self._libraries.get(avatar_id)
        if lib is None:
            return None
        if not lib.should_play():
            return None
        text, wav = lib.pick(category)
        lib.mark_played()
        return text, wav

    def get_all_texts(self) -> list[str]:
        """Return flat list of all unique backchannel texts (for generation scripts)."""
        texts = []
        for texts_list in BACKCHANNEL_LIBRARY.values():
            texts.extend(texts_list)
        return list(dict.fromkeys(texts))  # deduplicated, order preserved
