"""phase8_avatar_fields

Revision ID: 1e3da4b47230
Revises: 
Create Date: 2026-03-15 00:59:18.648455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3da4b47230'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # personality_prompt was already added in a partial prior run — skip if exists
    import sqlite3, os
    db_path = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'campaign.db')
    conn = sqlite3.connect(db_path)
    existing_cols = {r[1] for r in conn.execute('PRAGMA table_info(avatars)').fetchall()}
    conn.close()

    if 'personality_prompt' not in existing_cols:
        op.add_column('avatars', sa.Column('personality_prompt', sa.Text(), nullable=True))
    if 'verbosity' not in existing_cols:
        op.add_column('avatars', sa.Column('verbosity', sa.Float(), nullable=False, server_default='0.5'))
    if 'interrupts_often' not in existing_cols:
        op.add_column('avatars', sa.Column('interrupts_often', sa.Boolean(), nullable=False, server_default='0'))
    if 'personality_archetype' not in existing_cols:
        op.add_column('avatars', sa.Column('personality_archetype', sa.String(length=20), nullable=False, server_default='extrovert'))
    if 'holding_phrase_chance' not in existing_cols:
        op.add_column('avatars', sa.Column('holding_phrase_chance', sa.Float(), nullable=False, server_default='0.5'))
    if 'voice_id' not in existing_cols:
        op.add_column('avatars', sa.Column('voice_id', sa.String(length=100), nullable=True))
    if 'tts_engine_preference' not in existing_cols:
        op.add_column('avatars', sa.Column('tts_engine_preference', sa.String(length=20), nullable=False, server_default='auto'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatars', 'tts_engine_preference')
    op.drop_column('avatars', 'voice_id')
    op.drop_column('avatars', 'holding_phrase_chance')
    op.drop_column('avatars', 'personality_archetype')
    op.drop_column('avatars', 'interrupts_often')
    op.drop_column('avatars', 'verbosity')
    op.drop_column('avatars', 'personality_prompt')
    # ### end Alembic commands ###
